# nginx/nginx.conf

events {
    worker_connections 1024; # Nombre maximum de connexions par processus
}

http {
    # Groupe de serveurs backend pour le load balancing
    upstream coherent_text-apis {
        server coherent_text-api:8000;
        }
    # Définition du serveur http
    server {

        listen 80;
        server_name localhost; # Nom de domaine ou IP que ce bloc serveur gère

        # Redirige toutes les requêtes HTTP vers HTTPS
        return 301 https://$host$request_uri;

    }

    # Définition du serveur https
    server {
        listen 443 ssl; # Écoute sur le port 443 et active SSL
        server_name localhost; # Nom de domaine ou IP que ce serveur gère

        # Chemins vers les certificats SSL à l'intérieur du conteneur Nginx
        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        # Protocoles et chiffrements SSL
        ssl_protocols TLSv1.2 TLSv1.3; # N'autorise que les versions modernes de TLS
        ssl_ciphers HIGH:!aNULL:!MD5; # Liste des suites de chiffrement autorisées
        ssl_prefer_server_ciphers on; # Préfère les chiffrements du serveur

        # Toutes les requêtes qui commencent par /predict/ seront traitées ici
        location /predict {
            proxy_pass http://coherent_text-apis;
            # proxy_pass: Redirige la requête vers le groupe upstream

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

